name: Update Datasets

on:
  schedule:
    # Run every day at 6:00PM UTC.
    - cron: "0 18 * * *"

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Fetch fresh data
        run: python covid19_dash/data.py

      - name: Git Auto Commit
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          # Commit message
          commit_message: Update Datasets

          # Git branch name, where changes should be pushed to.
          # Required if Action is used on the `pull_request` event.
          branch: main

          # Commit options (eg. --no-verify)
          commit_options: -a

          # Add options (eg. -u)
          add_options: ""

          # Status options (eg. --untracked-files=no)
          status_options: ""

          # File pattern used for `git add`. For example `src/\*.js`
          file_pattern: covid-19-data/*.csv

          # Name used for the commit user
          commit_user_name: GitHub Actions

          # Email address used for the commit user
          commit_user_email: 41898282+github-actions[bot]@users.noreply.github.com

          # Value used for the commit author. Defaults to the username of whoever triggered this workflow run.
          commit_author: GitHub Actions <41898282+github-actions[bot]@users.noreply.github.com>

          # Message used to create a new git tag with the commit. Keep this empty, if no tag should be created.
          tagging_message: ""

          # Push options (eg. --force)
          push_options: ""
